@startuml  ### [C4] Каталог сущностей платформы

   !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
   !include https://gitlab.tes.store/tes-public/plantuml/-/raw/master/00.common/puml_styles.puml

    ' skinparam linetype polyline
    ' HIDE_STEREOTYPE()
    ' SHOW_PERSON_PORTRAIT()
    ' LAYOUT_TOP_DOWN()


'Компании, Организации

Container(GLONASS_ORG, "GLONASS", "Оператор телематических данных", "GLONASS", $sprite="electron_original", $tags="main")

Container(TTM_PLANT, "Производитель TU", "Блоки телематики, IoT", "REST_API", $sprite="mta", $tags="external")
Container(AGR_PLANT_SPB, "Производитель", "Автомобили", "REST_API", $sprite="car_side", $tags="external")
Container(CAR_DEALER, "Дилер", "Сервисный центр", "REST_API", $sprite="car_side", $tags="external")


@enduml
