    @startuml Контекст интеграции

' !include https://gpxlab.ru/hml_docs/inventory.puml
' !include https://gitlab.mobility.hyundai.ru/hml-public/plantuml/-/raw/master/common/inventory.puml
 !include https://gitlab.tes.store/tes-public/plantuml/-/raw/master/00.common/inventory.puml
 !include https://gitlab.tes.store/tes-public/plantuml/-/raw/master/01.nts/00.nts.inventory.puml

HIDE_STEREOTYPE()

'  LAYOUT_LANDSCAPE()
LAYOUT_TOP_DOWN()

    title
      Организация экземпляров TP для участников
      v2024.06.11
    end title

' НТС

    Rel_D(GLONASS_ORG, NTS_PLATFORM, "01. Управление платформой")

    Rel_L(NTS_CRM, NTS_PLATFORM_MANAGEMENT, "02.Конфигрураця экземпляра")
    Rel_R(NTS_CRM, NTS_BILLING,  "03. Начисления, платежи")

    Rel_D(NTS_PLATFORM_MANAGEMENT, NTS_FARM_INSTANCE_1,  "Управление экземпляром'")
    Rel_D(NTS_PLATFORM_MANAGEMENT, NTS_FARM_INSTANCE_2,  "Управление экземпляром")

    Rel_D(NTS_2_TELEMATIC_GATE,  MTA_DEVICE_PLANT_2, "TD, CMD", "пакеты TD, команды", "TCP, Redis", $tags="", $sprite="cog")

    Rel_D(NTS_1_TELEMATIC_GATE, MTA_DEVICE_PLANT, "TD, CMD", "пакеты TD, команды", "TCP, Redis", $tags="", $sprite="cog")
    Rel_D(NTS_1_CRM,              MTA_DEVICE_PLANT , "Управление клиентами", "ФЗ-152", "СУБД, DMZ", $sprite="people_group", $tags="critical")
    Rel_D(NTS_1_BILLING,          MTA_DEVICE_PLANT , "Начисления", "биллинговая информация", "REST_API", $sprite="calculator", $tags="gold")
    Rel_D(NTS_1_MARKETPLACE,      MTA_DEVICE_PLANT  , "Данные для управления услугами", "REST_API", $sprite="cogs", $tags="gold")

'  Поставщик услуг

    remove @unlinked

    @enduml