'!define DEVICONS https://gpxlab.ru/hml_docs/icons
'!define DEVICONS icons
!define DEVICONS https://gitlab.tes.store/tes-public/plantuml/-/raw/master/00.common/icons
'!define DEVICONS https://gitlab.mobility.hyundai.ru/hml-public/plantuml/-/raw/master/common/icons

!include DEVICONS/rabbitmq_original.puml
!include DEVICONS/cogs.puml
!include DEVICONS/cog.puml
!include DEVICONS/clickhouse.puml
!include DEVICONS/redis.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/mail.puml
!include DEVICONS/org.puml
!include DEVICONS/mobile.puml
!include DEVICONS/chrome.puml
!include DEVICONS/car_side.puml
!include DEVICONS/wallet.puml
!include DEVICONS/mta.puml
!include DEVICONS/electron_original.puml
!include DEVICONS/docker.puml
!include DEVICONS/gitlab.puml
!include DEVICONS/jenkins.puml
!include DEVICONS/tower_broadcast.puml
!include DEVICONS/mobile_alt.puml
!include DEVICONS/tools.puml
!include DEVICONS/dev.puml
!include DEVICONS/people_group.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5


!include <tupadr3/devicons2/java>
!include <tupadr3/devicons2/chrome>
!include <tupadr3/devicons2/postgresql>
!include <tupadr3/devicons/android>
!include <tupadr3/devicons2/chrome>
!include <tupadr3/devicons2/java>
!include <tupadr3/devicons2/postgresql>
!include <tupadr3/devicons2/nginx_original>
!include <tupadr3/devicons2/react_original>
!include <tupadr3/devicons2/android>
!include <tupadr3/devicons2/groovy>
!include <tupadr3/material/queue>
!include <tupadr3/material/mail>
!include <tupadr3/devicons2/dot_net_wordmark>
!include <tupadr3/devicons2/oracle_original>
!include <tupadr3/devicons/angular>
!include <office/Concepts/web_services>


AddElementTag("backendContainer", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#335DA5", $shape=EightSidedShape(), $legendText="legetText")
AddElementTag("backup", $fontColor="orange")
AddElementTag("violet", $bgColor="#9933bb", $borderColor="none")
AddElementTag("external", $bgColor="#999999", $borderColor="777777")
AddElementTag("main", $bgColor="#66bbbb")
AddElementTag("critical", $bgColor="#ff5533")
AddElementTag("seagreen", $bgColor="#2E8B57")
AddElementTag("gold", $bgColor="#f8c833")
AddElementTag("steel", $bgColor="#336592")
AddElementTag("mongo_green", $bgColor="#4DA449")
AddElementTag("mta", $bgColor="#4DA449")



AddElementTag("microService", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white", $legendText="micro service")
AddElementTag("car_side", $shape=EightSidedShape(), $bgColor="white",  $borderColor="white", $fontColor="#1345aa", $legendText=Car")
AddElementTag("step", $shape=RoundedBoxShape())
AddElementTag("mta", $shape=RoundedBoxShape(), $bgColor="#344755")
AddElementTag("rabbitmq_original", $sprite="rabbitmq_original,scale=0.7", $shape=RoundedBoxShape(), $bgColor="#f37332")
AddElementTag("electron_original", $shape=RoundedBoxShape(), $bgColor="#344755", $sprite="electron_original,scale=0.7")
AddElementTag("system_software", $bgColor="#0194C2", $borderColor="#00AE86")

