@startuml  ### [C4] Каталог сущностей платформы

   !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
   !include https://gitlab.tes.store/tes-public/plantuml/-/raw/master/00.common/puml_styles.puml

    skinparam linetype polyline
    HIDE_STEREOTYPE()
    SHOW_PERSON_PORTRAIT()
    LAYOUT_TOP_DOWN()

' Пользовательские Приложения

' Системы

System_Boundary(DC_PLATFORM_PLATFORM, "Платформа Цифрового автомобиля") {
ContainerDb(DC_PLATFORM_CLICKHOUSE_DB, "ClickHouse", "Колоночная аналитическая СУБД", "SQL", $tags="", $sprite="clickhouse")
Container(DC_PLATFORM_API, "Интеграционная подсистема", "Шлюз для участников", "REST_API, AMQP", $tags="", $sprite="cog")
Container(DC_PLATFORM_TELEMATIC_GATE, "Телематический шлюз", "Шлюз для телематических данных", "TCP, Redis", $tags="", $sprite="input")
Container(DC_PLATFORM_MOBILE, "Система обеспечения связи", "TCP,GPRS", "SIM-card", $tags="", $sprite="cogs")

System_Boundary(DC_PLATFORM_PLATFORM, "система Управления платформой Цифрового автомобиля") {
    Container(DC_PLATFORM_BILLING, "Система учета и тарификации", "Billing", "СУБД, web, backend", $tags="", $sprite="calculator")
    Container(DC_PLATFORM_MANAGEMENT, "Система управления платформой", "Мониторинг и управление данными", "СУБД, web, backend", $tags="", $sprite="cogs")
    Container(DC_PLATFORM_CRM_B2B, "Система управления участниками", "CRM B2B", "СУБД, web, backend", $tags="", $sprite="people_group")
    Container(DC_PLATFORM_CRM, "Система управление клиентами", "ФЗ-152", "СУБД, DMZ", $sprite="people_group", $tags="critical")
    Container(DC_PLATFORM_TELEMATIC_GATE, "-Каталог ТU\n- Шлюз TD\n- Система хранения TD\n- Система управления командами", "Телематический сервис", "TCP, Redis", $tags="", $sprite="cogs")
    Container(DC_PLATFORM_BILLING, "Услуги, биллинг", "Оператор сервиса", "REST_API", $sprite="calculator", $tags="gold")
    Container(DC_PLATFORM_MARKETPLACE, "- Маркетплейс\n- Система каталогов\n- Backend МП", "Сервисная платформа", "REST_API", $sprite="cogs", $tags="gold")
 }

}





' Внешние провайдеры сервисов


'Компании, Организации

Container(GLONASS_ORG, "GLONASS", "Оператор телематических данных", "GLONASS", $sprite="electron_original", $tags="main")

Container(MTA_DEVICE_PLANT, "Поставщик TU", "Блоки телематики, IoT", "REST_API", $sprite="mta", $tags="external")

Container(CAR_PLANT, "Производитель", "Автомобили", "REST_API", $sprite="car_side", $tags="external")
Container(CAR_DEALER, "Дилер", "Сервисный центр", "REST_API", $sprite="car_side", $tags="external")

' Базы данных
' Пользователи приложений, клиенты
' Пользователи CRM
' Разработка
' Шаги процесса
' Программное обеспечение



System_Boundary(MISOS, "Телематический блок MISOS DC") {
Container(MISOS_DC_SOFT, "Misos DC Software", "", "StdPeriphLib/STM32Cube",$sprite="cog",$tags="step")
Container(MISOS_DC_GPS_MODULE, "Модуль спутниковой навигации", "", $sprite="electron_original", $tags="step")
Container(MISOS_DC_GPRS_MODULE, "Модуль мобильной связи", "", $sprite="tower_broadcast", $tags="step")
Container(MISOS_DC_CONTROLLER, "Контроллер", "микроконтроллер семейства STM32G0x1", "", $sprite="microchip", $tags="step")
}


@enduml
