    @startuml Контекст интеграции

' !include https://gitlab.mobility.hyundai.ru/hml-public/plantuml/-/raw/master/common/inventory.puml

  !include https://gitlab.tes.store/tes-public/plantuml/-/raw/master/00.common/inventory.puml
  !include https://gitlab.tes.store/tes-public/plantuml/-/raw/master/02.agr/00.agr.inventory.puml
'  LAYOUT_LANDSCAPE()

    title
      <b>Взаимодействие участников телематической системы "Цифровой автомобиль"</b>
    end title

' AGR

    BiRel_R(AGR_SPB, TT, "1. Договор на проведение НИОКР, прототипирование, разработку РИД")
    BiRel_R(AGR_SPB, TT, "2. Договор на развитие платформы, сопровождение и техническую поддержку")
    Rel(AGR_SPB, DC_PLATFORM_CRM_B2B, "03. Управление участниками")
    Rel_D(CAR_DEALER, DC_PLATFORM_CRM_B2B, "API", "права доступа")

    Rel_L(DC_PLATFORM_MANAGEMENT, DC_PLATFORM_CRM_B2B,  "Управление доступом")
    Rel_D(AGR_SPB, DC_PLATFORM_MANAGEMENT, "04. Управление платформой")
    BiRel_R(DC_PLATFORM_MANAGEMENT, DC_PLATFORM_MOBILE_NETWORK,  "Учёт SIM-card")
    

'  Система управления платформой


    Rel_U(DC_PLATFORM_MARKETPLACE, DC_PLATFORM_CRM_B2B,  "05.Присоединение участника, отчеты", "API")
    Rel_D(DC_MOBILE_APP, DC_PLATFORM_MARKETPLACE, "Сервисы")
    Rel_R(DC_PLATFORM_BILLING, DC_PLATFORM_MARKETPLACE, "Сервисы")
    Rel_D(DC_PLATFORM_BILLING, DC_PLATFORM_DEVICES, "Device_id")
    BiRel_U(DC_PLATFORM_SERVICE_PROVIDER_GATE, DC_PLATFORM_BILLING, "service dataflow")
    Rel_D(DC_PLATFORM_DEVICES, DC_PLATFORM_CAR, "привязка VIN-Device_id")
    Rel_L(DC_PLATFORM_CAR, DC_PLATFORM_CRM, "привязка VIN-Client")


    Rel_U(MTA_DEVICE, DC_PLATFORM_TELEMATIC_GATE, "raw telematic data", "device_id")
    Rel_R(DC_PLATFORM_TELEMATIC_GATE, DC_PLATFORM_MANAGEMENT, "telematic data", "device_id, data")


    Rel_U(DC_PLATFORM_DEVICES, MTA_DEVICE , "управление", "настройка блока")
    Rel_L(CAR_PLANT, DC_PLATFORM_CAR, "API", "связь VIN и device_id")


    remove @unlinked

    @enduml